### ISSUE TITLE
No usable constructor for java.time.Period

### ISSUE THREAD

**Issue by jvence** [jmkgreen/morphia#77]
I'm trying to load an instance of a class that contains a Period and keep getting "org.mongodb.morphia.mapping.MappingException: No usable constructor for java.time.Period"

I know that this is probably caused by the fact that Period doesn't have an empty constructor but given that it's a standard datatype in Java 8, I'm assuming that is should work. Same issue for LocalDateTime.

I am using 1.2.0-SNAPSHOT.

Any workaround for this?

**Comment by jmkgreen** [comment]
Please switch this over to the official project (as has been for a long time):

https://github.com/mongodb/morphia

Closing this down.
